---
- name: Build Switch configuration
  hosts: DC1_FABRIC
  connection: local
  gather_facts: no

  tasks:

    - name: generate intented variables
      tags: [build]
      import_role:
         name: arista.avd.eos_l3ls_evpn

    - name: generate device intended config and documention
      tags: [build]
      import_role:
         name: arista.avd.eos_cli_config_gen

- name: Configuration deployment with CVP
  hosts: CVP-1
  connection: local
  gather_facts: no

  tasks:

    - name: upload cvp configlets
      import_role:
          name: arista.avd.cvp_configlet_upload
      vars:
        configlets_cvp_prefix: 'DC1-CUSTOM'
        configlet_directory: "{{inventory_dir}}/configlets"

    - name: run CVP provisioning
      import_role:
         name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'DC1_FABRIC'
        configlets_prefix: 'DC1-AVD'
        device_filter: 'DC1'
        state: present