# DC1 Tenants Networks
# Documentation of Tenant specific information - Vlans/VRFs

tenants:

# Tenant A Specific Information - VRFs / VLANs
  Tenant_A:
    mac_vrf_vni_base: 20000
    vrfs:
      Tenant_A_OP_Zone:
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.2.0/24
        svis:
          210:
            name: Tenant_A_OP_Zone_1
            tags: [ opzone ]
            enabled: true
            ip_address_virtual: 10.2.10.1/24
          211:
            name: Tenant_A_OP_Zone_2
            tags: [ opzone ]
            enabled: true
            ip_address_virtual: 10.2.11.1/24
# virtual ip address router-virtual
          212:
            name: Tenant_A_OP_Zone_3
            tags: [ DC1_LEAF2 ]
            enabled: true
            ip_virtual_router_address: 10.2.12.1/24
            nodes:
              DC1-LEAF2A:
                ip_address: 10.2.12.2/24
              DC1-LEAF2B:
                ip_address: 10.2.12.3/24

      Tenant_A_WEB_Zone:
        vrf_vni: 11
        svis:
          220:
            name: Tenant_A_WEB_Zone_1
            tags: [ web, erp1 ]
            enabled: true
            ip_address_virtual: 10.2.20.1/24
          221:
            name: Tenant_A_WEBZone_2
            tags: [ web ]
            enabled: true
            ip_address_virtual: 10.2.21.1/24
      # Tenant_A_APP_Zone:
      #   vrf_vni: 12
      #   svis:
      #     230:
      #       name: Tenant_A_APP_Zone_1
      #       tags: [ app, erp1 ]
      #       enabled: true
      #       ip_address_virtual: 10.2.30.1/24
      #     231:
      #       name: Tenant_A_APP_Zone_2
      #       tags: [ app ]
      #       enabled: true
      #       ip_address_virtual: 10.2.31.1/24


    l2vlans:
      # 260:
      #   name: Tenant_A_VMOTION
      #   tags: [ vmotion ]
      261:
        name: Tenant_A_NFS
        tags: [ nfs ]
