port_profiles:


  TENANT_A_OPZone:
    mode: access
    vlans: "110"

  TENANT_A_ALL:
    mode: trunk
    vlans: "120-130,160-161"

servers:

  server-1:
    rack: RackB
    adapters:
      - server_ports: [ Eth1 ]
        switch_ports: [ Ethernet3 ]
        switches: [ DC1-L2LEAF1A ]
        profile: TENANT_A_OPZone
      - server_ports: [ Eth2, Eth3 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ DC1-LEAF2A, DC1-LEAF2B ]
        profile: TENANT_A_ALL
        port_channel:
          state: present
          description: PortChanne1
          mode: active