---
- name: Upload configlet to Cloudvision
  hosts: CVP-1
  connection: local
  gather_facts: false
  vars:
    configlets_prefix_var: "DCI"
    configlet_dir_var: "{{inventory_dir}}/configlets/"
    configlet_file_extension: 'conf'
  tasks:
  - name: 'upload configlets to cloudvision {{inventory_hostname}}'
    import_role:
      name: arista.avd.cvp_configlet_upload
    vars:
      configlet_directory: '{{ configlet_dir_var }}'
      configlets_cvp_prefix: '{{ configlets_prefix_var }}'
      file_extension: '{{configlet_file_extension}}'