---
- name: Build Switch configuration
  hosts: DC2_FABRIC
  connection: local
  gather_facts: no

  tasks:

    - name: include global_vars
      tags: [build, provision]
      include_vars: "{{ item }}"
      with_items:
        - "../global_vars/AVD_LAB.yml"
        - "../global_vars/EOS.yml"

    - name: generate intented variables
      tags: [build]
      import_role:
         name: arista.avd.eos_l3ls_evpn

    - name: generate intented DCI variables
      tags: [build, provision]
      import_role:
         name: eos_dci

    - name: generate device intended config and documention
      tags: [build]
      import_role:
         name: arista.avd.eos_cli_config_gen

- name: Configuration deployment with CVP
  hosts: CVP-1
  connection: local
  gather_facts: no

  tasks:

    - name: upload cvp configlets
      import_role:
          name: arista.avd.cvp_configlet_upload
      vars:
        configlets_cvp_prefix: 'DC2-CUSTOM'
        configlet_directory: "{{inventory_dir}}/configlets"

    - name: run CVP provisioning
      import_role:
         name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'DC2_FABRIC'
        configlets_prefix: 'DC2-AVD'
        device_filter: 'DC2'
        state: present