
name: Ansible Code Execution
on: [push]
jobs:
  'ansible_CI':
    name: Run Ansible Playbooks
    runs-on: ubuntu-latest
    container: avdteam/base:centos-8
    steps:
      - uses: actions/checkout@master
      - name: 'Install collections'
        run: make install

      - name: 'Build AVD content'
        run: |
          make dc-build

      - name: 'Save Python libs version'
        run: |
          pip3 freeze
          pip3 freeze > inventory/intended/pip-version.txt

      - uses: actions/upload-artifact@v1
        with:
          name: intended-files
          path: inventories/