name: Commit check
on:
  push:
  pull_request:
jobs:
  'pre-commit':
    name: Run pre-commit validation hooks
    runs-on: ubuntu-latest
    container: avdteam/base:centos8
    steps:
      - uses: actions/checkout@master
      - name: 'Pre Commit run'
        run: |
          pre-commit run
